print("Hello friend. I heard you are re painting one wall in your room. ")
print("What is width of the wall?")
width_total = input()
print("What is the height of the wall?")
height_total = input()
print("How much does a gallon of paint costs at your local paint store?")
paint_cost = input()
