print('Hello')
print('What is your character name')
name = input()
print('Pick a character type')
character = input()
print('You can only have a total of 100 magic and attack points combined.')
print('How many magic points do you want?')
magic = input()
print('How many attack points do you want?')
attack = input()
print("You have chosen the character name" , name , "and character type" , character , "you have", magic , "magic points and" , attack , 'attack points.' )
